meta_product_name: "SoCo"
meta_title: "SoCo - Make New Social Connections"
meta_description: "SoCo favorise les connections sociales, via des événements auxquels participent les utilisateurs, ou dont ils sont les organisateurs.""
twitter_account: "@product_twitter_account"   # required for Twitter Cards
